name: Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v6.4.0
        with:
          go-version: "1.25"

      - name: Generate assets
        run: go run build.go assets

      - name: Build
        run: go build ./lib/... ./cmd/...

      - name: Test
        run: go test -count=1 -timeout 120s -short ./lib/...
